### ISSUE TITLE
Is there a trained model and inference script with sample data?

### ISSUE THREAD

**Issue by tonyreina** [toddhollon/srh_cnn#1]
I'd like to use this model and a sample training script for our reference sample applications (https://github.com/intel-iot-devkit/iot-devcloud/blob/master/python/pneumonia-classification/classification_pneumonia.ipynb).

Is this possible?  Does the model, code, and/or dataset have an associated license? Any commercial restrictions to using them?

Thanks.
-Tony

**Comment by Daniel0520** [comment]
Hi! I would be also interested in it!
